// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(public)/componentes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/componentes">> = Specific
  const handler = {} as typeof import("../../app/(public)/componentes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/contacto/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contacto">> = Specific
  const handler = {} as typeof import("../../app/(public)/contacto/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/laboratorio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/laboratorio">> = Specific
  const handler = {} as typeof import("../../app/(public)/laboratorio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/novedades/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/novedades/[slug]">> = Specific
  const handler = {} as typeof import("../../app/(public)/novedades/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/novedades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/novedades">> = Specific
  const handler = {} as typeof import("../../app/(public)/novedades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/nuestra-red/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nuestra-red">> = Specific
  const handler = {} as typeof import("../../app/(public)/nuestra-red/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/nuestros-servicios/[vertical]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nuestros-servicios/[vertical]">> = Specific
  const handler = {} as typeof import("../../app/(public)/nuestros-servicios/[vertical]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/nuestros-servicios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nuestros-servicios">> = Specific
  const handler = {} as typeof import("../../app/(public)/nuestros-servicios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/proyectos/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/proyectos/[slug]">> = Specific
  const handler = {} as typeof import("../../app/(public)/proyectos/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/proyectos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/proyectos">> = Specific
  const handler = {} as typeof import("../../app/(public)/proyectos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/sobre-facttic/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sobre-facttic">> = Specific
  const handler = {} as typeof import("../../app/(public)/sobre-facttic/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/suma-tu-coop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suma-tu-coop">> = Specific
  const handler = {} as typeof import("../../app/(public)/suma-tu-coop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/clientes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clientes/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/clientes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/clientes/nueva/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clientes/nueva">> = Specific
  const handler = {} as typeof import("../../app/admin/clientes/nueva/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clientes">> = Specific
  const handler = {} as typeof import("../../app/admin/clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/consejo/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/consejo/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/consejo/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/consejo/nueva/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/consejo/nueva">> = Specific
  const handler = {} as typeof import("../../app/admin/consejo/nueva/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/consejo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/consejo">> = Specific
  const handler = {} as typeof import("../../app/admin/consejo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/cooperativas/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cooperativas/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/cooperativas/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/cooperativas/nueva/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cooperativas/nueva">> = Specific
  const handler = {} as typeof import("../../app/admin/cooperativas/nueva/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/cooperativas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cooperativas">> = Specific
  const handler = {} as typeof import("../../app/admin/cooperativas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/ingresar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ingresar">> = Specific
  const handler = {} as typeof import("../../app/admin/ingresar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/novedades/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/novedades/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/novedades/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/novedades/nueva/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/novedades/nueva">> = Specific
  const handler = {} as typeof import("../../app/admin/novedades/nueva/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/novedades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/novedades">> = Specific
  const handler = {} as typeof import("../../app/admin/novedades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/organizaciones/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/organizaciones/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/organizaciones/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/organizaciones/nueva/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/organizaciones/nueva">> = Specific
  const handler = {} as typeof import("../../app/admin/organizaciones/nueva/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/organizaciones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/organizaciones">> = Specific
  const handler = {} as typeof import("../../app/admin/organizaciones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/proyectos/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/proyectos/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/proyectos/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/proyectos/nueva/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/proyectos/nueva">> = Specific
  const handler = {} as typeof import("../../app/admin/proyectos/nueva/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/proyectos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/proyectos">> = Specific
  const handler = {} as typeof import("../../app/admin/proyectos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/sectores/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sectores/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/sectores/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/sectores/nueva/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sectores/nueva">> = Specific
  const handler = {} as typeof import("../../app/admin/sectores/nueva/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/sectores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sectores">> = Specific
  const handler = {} as typeof import("../../app/admin/sectores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/servicios/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/servicios/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/servicios/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/servicios/nueva/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/servicios/nueva">> = Specific
  const handler = {} as typeof import("../../app/admin/servicios/nueva/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/servicios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/servicios">> = Specific
  const handler = {} as typeof import("../../app/admin/servicios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tecnologias/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tecnologias/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/tecnologias/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tecnologias/nueva/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tecnologias/nueva">> = Specific
  const handler = {} as typeof import("../../app/admin/tecnologias/nueva/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tecnologias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tecnologias">> = Specific
  const handler = {} as typeof import("../../app/admin/tecnologias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contacto/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contacto">> = Specific
  const handler = {} as typeof import("../../app/api/contacto/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/lugares/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lugares">> = Specific
  const handler = {} as typeof import("../../app/api/lugares/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/media/[filename]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/[filename]">> = Specific
  const handler = {} as typeof import("../../app/api/media/[filename]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
