// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/clientes" | "/admin/clientes/[id]" | "/admin/clientes/nueva" | "/admin/consejo" | "/admin/consejo/[id]" | "/admin/consejo/nueva" | "/admin/cooperativas" | "/admin/cooperativas/[id]" | "/admin/cooperativas/nueva" | "/admin/ingresar" | "/admin/novedades" | "/admin/novedades/[id]" | "/admin/novedades/nueva" | "/admin/organizaciones" | "/admin/organizaciones/[id]" | "/admin/organizaciones/nueva" | "/admin/proyectos" | "/admin/proyectos/[id]" | "/admin/proyectos/nueva" | "/admin/sectores" | "/admin/sectores/[id]" | "/admin/sectores/nueva" | "/admin/servicios" | "/admin/servicios/[id]" | "/admin/servicios/nueva" | "/admin/tecnologias" | "/admin/tecnologias/[id]" | "/admin/tecnologias/nueva" | "/componentes" | "/contacto" | "/novedades" | "/novedades/[slug]" | "/nuestra-red" | "/nuestros-servicios" | "/nuestros-servicios/[vertical]" | "/proyectos" | "/proyectos/[slug]" | "/sobre-facttic" | "/suma-tu-coop"
type AppRouteHandlerRoutes = "/api/contacto" | "/api/lugares" | "/api/media/[filename]"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/clientes": {}
  "/admin/clientes/[id]": { "id": string; }
  "/admin/clientes/nueva": {}
  "/admin/consejo": {}
  "/admin/consejo/[id]": { "id": string; }
  "/admin/consejo/nueva": {}
  "/admin/cooperativas": {}
  "/admin/cooperativas/[id]": { "id": string; }
  "/admin/cooperativas/nueva": {}
  "/admin/ingresar": {}
  "/admin/novedades": {}
  "/admin/novedades/[id]": { "id": string; }
  "/admin/novedades/nueva": {}
  "/admin/organizaciones": {}
  "/admin/organizaciones/[id]": { "id": string; }
  "/admin/organizaciones/nueva": {}
  "/admin/proyectos": {}
  "/admin/proyectos/[id]": { "id": string; }
  "/admin/proyectos/nueva": {}
  "/admin/sectores": {}
  "/admin/sectores/[id]": { "id": string; }
  "/admin/sectores/nueva": {}
  "/admin/servicios": {}
  "/admin/servicios/[id]": { "id": string; }
  "/admin/servicios/nueva": {}
  "/admin/tecnologias": {}
  "/admin/tecnologias/[id]": { "id": string; }
  "/admin/tecnologias/nueva": {}
  "/api/contacto": {}
  "/api/lugares": {}
  "/api/media/[filename]": { "filename": string; }
  "/componentes": {}
  "/contacto": {}
  "/novedades": {}
  "/novedades/[slug]": { "slug": string; }
  "/nuestra-red": {}
  "/nuestros-servicios": {}
  "/nuestros-servicios/[vertical]": { "vertical": string; }
  "/proyectos": {}
  "/proyectos/[slug]": { "slug": string; }
  "/sobre-facttic": {}
  "/suma-tu-coop": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
